[CARRO]
nome = Corolla Altis
preco = 45000
info_concessionaria = Toyota Corolla Altis Dois Ponto Zero. Preço: Quarenta e cinco mil créditos. Extremamente silencioso, confortável e o queridinho dos passageiros de aplicativo!
historico = Corolla Altis 2020. O sedan médio mais vendido e respeitado do país. Famoso por sua durabilidade extrema, conforto a bordo, consumo moderado e excelente espaço interno. O veículo ideal para quem quer faturar alto no Uber Comfort e Black, oferecendo uma viagem extremamente suave e silenciosa para seus clientes.
pecas = Motor 2.0 Dynamic Force Dual VVT-i, Transmissão Direct Shift CVT que simula marchas, Suspensão Traseira Independente Double Wishbone, Isolamento Acústico Premium de Cabine

# Loops de pista e pneus específicos para o Corolla
asfalto_loop = audio/carros/corolla/asfalto_loop.wav
terra_loop = audio/carros/corolla/terra_loop.wav
lama_loop = audio/carros/corolla/lama_loop.wav
estrada_loop = audio/carros/corolla/estrada_loop.wav
rua_loop = audio/carros/corolla/rua_loop.wav

# Sons de abrir e fechar o vidro do Corolla
abrir_vidro = audio/carros/corolla/abrir_vidro.wav
fechar_vidro = audio/carros/corolla/fechar_vidro.wav

[FISICA]
rpm_lenta = 800
rpm_max = 6600
rev_limiter = 6500

[MARCHA_1]
vel_max = 60.0
forca = 0.52
rpm_up = 4200

[MARCHA_2]
vel_max = 110.0
forca = 0.38
rpm_up = 4800
rpm_down = 1800

[MARCHA_3]
vel_max = 190.0
forca = 0.26
rpm_down = 2000
