[CARRO]
# Nome do veículo que aparecerá nos menus, concessionária e falas do GPS
nome = Gol Quadrado

# Preço de compra na Concessionária (em créditos)
preco = 12000

# Texto falado pelo sintetizador ao visualizar o carro na Concessionária
info_concessionaria = Gol Quadrado Um Ponto Seis AP. Preço: Doze mil créditos. Muito potente, clássico e robusto!

# História/Curiosidades do carro falado no menu de detalhes da Garagem
historico = Gol Quadrado Um Ponto Seis com motor AP. O queridinho das ruas brasileiras, excelente torque, muito robusto e de fácil preparação.

# Lista de itens mecânicos instalados inicialmente separados por vírgula
pecas = Motor AP 1.6, Carburador Web 2E Regulado, Câmbio AP de 5 Marchas Longo, Escapamento Esportivo JK

# Configurações opcionais de loops de pista/pneu personalizados para este carro.
# Caso queira usar arquivos de áudio customizados para os diferentes ambientes, coloque os arquivos de som .wav
# dentro da pasta do respectivo carro e configure o caminho relativo abaixo.
# Se não existirem ou forem deixados vazios, o jogo usará automaticamente os sons padrão contidos na pasta audio/pista_ambiente/
asfalto_loop = audio/carros/gol/asfalto_loop.wav
terra_loop = audio/carros/gol/terra_loop.wav
lama_loop = audio/carros/gol/lama_loop.wav
estrada_loop = audio/carros/gol/estrada_loop.wav
rua_loop = audio/carros/gol/rua_loop.wav

[FISICA]
# Rotação da marcha lenta (RPM) do motor parado
rpm_lenta = 850

# Rotação limite máxima permitida no conta-giros do painel (RPM)
rpm_max = 7200

# Ponto de corte do limitador de giro do motor (RPM)
rev_limiter = 6700

# Configurações das marchas do Câmbio Automático
[MARCHA_1]
# Velocidade limite da 1ª marcha em km/h
vel_max = 55.0
# Multiplicador de força de torque da marcha (aceleração inicial)
forca = 0.65
# Rotação (RPM) necessária para subir a marcha para a 2ª
rpm_up = 4500

[MARCHA_2]
# Velocidade limite da 2ª marcha em km/h
vel_max = 105.0
# Multiplicador de força de torque da marcha
forca = 0.40
# Rotação (RPM) necessária para subir a marcha para a 3ª
rpm_up = 5200
# Rotação (RPM) que faz o câmbio reduzir para a 1ª marcha
rpm_down = 1800

[MARCHA_3]
# Velocidade limite da 3ª marcha em km/h
vel_max = 165.0
# Multiplicador de força de torque da marcha
forca = 0.25
# Rotação (RPM) que faz o câmbio reduzir para a 2ª marcha
rpm_down = 2000
